KnightBus.sln, knightbus-microsoft-dependencyinjection/src/KnightBus.Microsoft.DependencyInjection/KnightBus.Microsoft.DependencyInjection.csproj, knightbus-microsoft-dependencyinjection/src/KnightBus.Microsoft.DependencyInjection/MicrosoftDependencyInjectionExtensions.cs, knightbus-microsoft-dependencyinjection/src/KnightBus.Microsoft.DependencyInjection/MicrosoftDependencyInjectionProcessorProvider.cs, knightbus-microsoft-dependencyinjection/src/KnightBus.Microsoft.DependencyInjection/MicrosoftDependencyInjectionScopedLifeStyleMiddleware.cs
Vi behöver utöka KnightWatch också så att den kan använda sig av denna container också
=> Added Microsoft.Extension.DependencyInjection support to KnightBus

knightbus-applicationinsights/src/KnightBus.ApplicationInsights/KnightBus.ApplicationInsights.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusQueueChannelReceiver.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusTopicChannelReceiver.cs, knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-microsoft-dependencyinjection/src/KnightBus.Microsoft.DependencyInjection/KnightBus.Microsoft.DependencyInjection.csproj, knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj, knightbus-schedule/src/KnightBus.Schedule/JobExecutor.cs, knightbus-schedule/src/KnightBus.Schedule/KnightBus.Schedule.csproj, knightbus-serilog/src/KnightBus.Serilog/KnightBus.Serilog.csproj, knightbus-simpleinjector/src/KnightBus.SimpleInjector/KnightBus.SimpleInjector.csproj, knightbus-sqlserver/src/KnightBus.SqlServer/KnightBus.SqlServer.csproj, knightbus/src/KnightBus.Core/KnightBus.Core.csproj, knightbus/src/KnightBus.Core/Singleton/SingletonTimerScope.cs, knightbus/src/KnightBus.Host/KnightBus.Host.csproj, knightbus/src/KnightBus.Host/Singleton/SingletonChannelReceiver.cs, knightbus/tests/KnightBus.Host.Tests.Unit/SingletonChannelReceiverTests.cs, knightbus/tests/KnightBus.Host.Tests.Unit/SingletonTransportStarterTests.cs
Fix bug where losing the singleton lock would both produce warnings and still leave the original processor running
=> Stop channel recievers

knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/StorageQueueClient.cs
Requeue deadletters and the possibility to decide on each message if it should be requeued or not
=> Requeue deadletters on the storage bus

knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj, knightbus-redis/src/KnightBus.Redis/RedisChannelReceiver.cs, knightbus-redis/src/KnightBus.Redis/RedisManagementClient.cs, knightbus-redis/src/KnightBus.Redis/RedisMessageStateHandler.cs, knightbus-redis/src/KnightBus.Redis/RedisQueueClient.cs
Add RedisManagementClient and functionality to requeue deadletters along with a couple of methods to get queue count by type or queuename.
=> Requeue redis deadletters

KnightBus.sln, README.md, documentation/source/index.rst, documentation/source/monitoring.rst, knightbus-newrelic/src/KnightBus.NewRelic/KnightBus.NewRelic.csproj, knightbus-newrelic/src/KnightBus.NewRelic/NewRelicExtensions.cs, knightbus-newrelic/src/KnightBus.NewRelic/NewRelicMessageMiddleware.cs
Add NewRelicMessageMiddleware. @hartenb you did something similar before, does this look right?
=> Add NewRelicMessageMiddleware

README.md, documentation/source/monitoring.rst
Just some documentation updates
=> Improve docs for newrelic

README.md, documentation/source/quickstart.rst, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusQueueChannelReceiver.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusTopicChannelReceiver.cs, knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/StorageQueueMessagePump.cs, knightbus-azurestorage/tests/KnightBus.Azure.Storage.Tests.Unit/StorageQueueMessagePumpTests.cs, knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj, knightbus-redis/src/KnightBus.Redis/RedisChannelReceiver.cs, knightbus/src/KnightBus.Host/KnightBus.Host.csproj, knightbus/src/KnightBus.Host/KnightBusHost.cs, knightbus/src/KnightBus.Host/KnightBusHostExtensions.cs, knightbus/tests/KnightBus.Host.Tests.Unit/KnightBus.Host.Tests.Unit.csproj
Implement IHostedService to make sure we can detect shutdown signals SIGTERM
=> Graceful shutdown

knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusQueueChannelReceiver.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusTopicChannelReceiver.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/StoppableMessageReceiver.cs
See https://github.com/Azure/azure-service-bus-dotnet/blob/ab1a347a2d9b52321d82a7e7862141520315ad9a/src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs
=> close the pump instead of closing the connection

knightbus-applicationinsights/src/KnightBus.ApplicationInsights/KnightBus.ApplicationInsights.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusQueueChannelReceiver.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusTopicChannelReceiver.cs, knightbus-azureservicebus/tests/KnightBus.Azure.ServiceBus.Unit/ServiceBusTests.cs, knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/StorageQueueMessagePump.cs, knightbus-microsoft-dependencyinjection/src/KnightBus.Microsoft.DependencyInjection/KnightBus.Microsoft.DependencyInjection.csproj, knightbus-newrelic/src/KnightBus.NewRelic/KnightBus.NewRelic.csproj, knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj, knightbus-redis/src/KnightBus.Redis/RedisChannelReceiver.cs, knightbus-redis/src/KnightBus.Redis/RedisQueueClient.cs, knightbus-redis/tests/KnightBus.Redis.Tests.Integration/RedisSagaStoreTests.cs, knightbus-schedule/src/KnightBus.Schedule/JobExecutor.cs, knightbus-schedule/src/KnightBus.Schedule/KnightBus.Schedule.csproj, knightbus-serilog/src/KnightBus.Serilog/KnightBus.Serilog.csproj, knightbus-simpleinjector/src/KnightBus.SimpleInjector/KnightBus.SimpleInjector.csproj, knightbus-simpleinjector/src/KnightBus.SimpleInjector/SimpleInjectorScopedLifeStyleMiddleware.cs, knightbus-sqlserver/src/KnightBus.SqlServer/KnightBus.SqlServer.csproj, knightbus/src/KnightBus.Core/DefaultMiddlewares/ExtendMessageLockDurationMiddleware.cs, knightbus/src/KnightBus.Core/KnightBus.Core.csproj, knightbus/src/KnightBus.Host/KnightBus.Host.csproj, knightbus/src/KnightBus.Host/KnightBusHost.cs, knightbus/src/KnightBus.Host/Singleton/SingletonChannelReceiver.cs, knightbus/tests/KnightBus.DependencyInjection.Tests.Unit/MicrosoftDependencyInjectionTests.cs, knightbus/tests/KnightBus.DependencyInjection.Tests.Unit/SimpleInjectorTests.cs, knightbus/tests/KnightBus.Shared.Tests.Integration/SagaStoreTests.cs
Dispose cts and make sure it's done without introducing AlreadyDisposedExceptions
=> Cts memory leak

knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs, knightbus-azurestorage/tests/KnightBus.Azure.Storage.Tests.Integration/BlobSagaStorageTests.cs
=> Blob saga storage

knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj, knightbus-redis/src/KnightBus.Redis/RedisConfiguration.cs
Copy-paste from IStorageBusConfiguration. We register these configurations for health checks and need to do it for redis as well.
=> Add IRedisConfiguration to be able to register configuration in DI

knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusQueueChannelReceiver.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusTopicChannelReceiver.cs
Had a hard time finding why a pod didn't start so this PR should make it easier to see it in the logs.
=> Log exception when creating queue or topic

knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj
Pre 5.0.0 version of Microsoft.Azure.ServiceBus contains a bug which causes issues on NET Core 5.0
https://github.com/Azure/azure-sdk-for-net/issues/13899
=> Update Microsoft.Azure.ServiceBus 4.1.4 -> 5.0.0

knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/Singleton/BlobLockManager.cs, knightbus-azurestorage/src/KnightBus.Azure.Storage/Singleton/DefaultBlobLockScheme.cs, knightbus-azurestorage/src/KnightBus.Azure.Storage/StorageExtensions.cs
We'll need this when running two parallel ServiceBus instances
=> Add the option to manually supply a custom lock scheme

knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/CHANGELOG.md, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ClientFactory.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/IServiceBusConfiguration.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusChannelReceiverBase.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusConfiguration.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusSharedConnectionConfiguration.cs
Setup client factory based on configuration and enable support for using shared connection of service bus client
=> Shared connection

knightbus-applicationinsights/src/KnightBus.ApplicationInsights/KnightBus.ApplicationInsights.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/Sagas/BlobSagaStore.cs, knightbus-azurestorage/tests/KnightBus.Azure.Storage.Tests.Integration/BlobSagaStorageTests.cs, knightbus-nats/src/KnightBus.Nats/KnightBus.Nats.csproj, knightbus-newrelic/src/KnightBus.NewRelic/KnightBus.NewRelic.csproj, knightbus-redis/src/KnightBus.Redis/KnightBus.Redis.csproj, knightbus-redis/src/KnightBus.Redis/RedisSagaStore.cs, knightbus-schedule/src/KnightBus.Schedule/KnightBus.Schedule.csproj, knightbus-sqlserver/src/KnightBus.SqlServer/KnightBus.SqlServer.csproj, knightbus-sqlserver/src/KnightBus.SqlServer/SqlServerSagaStore.cs, knightbus/examples/KnightBus.Examples.Azure.Storage/Program.cs, knightbus/examples/KnightBus.Examples.Redis/Program.cs, knightbus/src/KnightBus.Core/Changelog.md, knightbus/src/KnightBus.Core/KnightBus.Core.csproj, knightbus/src/KnightBus.Core/Sagas/Exceptions/SagaDataConflictException.cs, knightbus/src/KnightBus.Core/Sagas/ISagaStore.cs, knightbus/src/KnightBus.Core/Sagas/Saga.cs, knightbus/src/KnightBus.Core/Sagas/SagaHandler.cs, knightbus/src/KnightBus.Core/Sagas/SagaMiddleWare.cs, knightbus/src/KnightBus.Host/KnightBus.Host.csproj, knightbus/tests/KnightBus.Core.Tests.Unit/SagaHandlerTests.cs, knightbus/tests/KnightBus.Core.Tests.Unit/SagaMiddlewareTests.cs, knightbus/tests/KnightBus.Shared.Tests.Integration/SagaStoreTests.cs
Throw an exception when updating saga data if the data has been modified since reading it
* Interface for `ISagaData`?
* I'd like to hide `SagaData<T>` completely from the class that's implementing `Saga<T>`
=> Throw if etag differs when updating blob saga

knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Management/KnightBus.Azure.ServiceBus.Management.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Management/ServiceBusQueueManager.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Management/ServiceBusSubscriptionManager.cs, knightbus-azurestorage/src/KnightBus.Azure.Storage.Management/KnightBus.Azure.Storage.Management.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage.Management/StorageQueueManager.cs, knightbus-postgresql/src/KnightBus.PostgreSql.Management/KnightBus.PostgreSql.Management.csproj, knightbus-postgresql/src/KnightBus.PostgreSql.Management/PostgresQueueManager.cs, knightbus-redis/src/KnightBus.Redis.Management/KnightBus.Redis.Management.csproj, knightbus-redis/src/KnightBus.Redis.Management/RedisQueueManager.cs, knightbus/src/KnightBus.Core.Management/KnightBus.Core.Management.csproj, knightbus/src/KnightBus.Core.Management/QueueMessage.cs
Add ScheduledTime property to QueueMessage. Primarily used for ServiceBus queue messages.
=> Add ScheduledTime property to QueueMessage

knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Management/KnightBus.Azure.ServiceBus.Management.csproj, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Management/ServiceBusExtensions.cs, knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus.Management/ServiceBusQueueManager.cs, knightbus-postgresql/src/KnightBus.PostgreSql.Management/KnightBus.PostgreSql.Management.csproj, knightbus-postgresql/src/KnightBus.PostgreSql.Management/PostgresManagementClient.cs, knightbus-postgresql/src/KnightBus.PostgreSql.Management/PostgresQueueExtensions.cs, knightbus-postgresql/src/KnightBus.PostgreSql.Management/PostgresQueueManager.cs, knightbus-postgresql/tests/KnightBus.PostgreSql.Tests.Integration/PostgresBusTests.cs, knightbus/examples/KnightBus.Examples.Azure.ServiceBus/KnightBus.Examples.Azure.ServiceBus.csproj, knightbus/examples/KnightBus.Examples.Azure.ServiceBus/Program.cs, knightbus/src/KnightBus.Core.Management/IQueueMessageSender.cs, knightbus/src/KnightBus.Core.Management/KnightBus.Core.Management.csproj
Supports postgres and azure service bus transports
=> Add managment support for sending untyped messages

knightbus-postgresql/src/KnightBus.PostgreSql/Changelog.md, knightbus-postgresql/src/KnightBus.PostgreSql/KnightBus.PostgreSql.csproj
Forgot to bump Knightbus.PostgreSql in #131
=> fix: bump Knightbus.PostgreSql

knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/KnightBus.Azure.ServiceBus.csproj, knightbus-azurestorage/src/KnightBus.Azure.Storage/KnightBus.Azure.Storage.csproj, knightbus-sqlserver/src/KnightBus.SqlServer/KnightBus.SqlServer.csproj
https://github.com/advisories/GHSA-ch6p-4jcm-h8vh
=> fix: security vulnerability in System.Text.Encodings.Web
